/**
 * Pre-built quest ideas the user can drop into their backlog with one click,
 * mirroring how skill templates work. Activating a template creates a new
 * quest in the user's backlog (status = "backlog") and stamps templateId so
 * we can hide it from the gallery.
 */

export type QuestTemplate = {
  id: string;
  type: "main" | "side";
  name: string;
  description: string;
  icon: string;
  xpReward: number;
  category: string; // grouping label for the template gallery
  tasks?: string[];
};

export const QUEST_TEMPLATES: QuestTemplate[] = [
  // ===== Health & Body =====
  {
    id: "run-5k",
    type: "side",
    category: "Health & Body",
    name: "Run a 5K",
    description: "Build up to running 5 kilometers without stopping.",
    icon: "🏃",
    xpReward: 75,
    tasks: [
      "Walk 30 minutes / 3× this week",
      "Run-walk intervals for 2 weeks",
      "Run 3K continuously",
      "Run 5K continuously",
    ],
  },
  {
    id: "lose-5kg",
    type: "main",
    category: "Health & Body",
    name: "Lose 5kg the healthy way",
    description: "Sustainable weight loss through habits, not crash diets.",
    icon: "💪",
    xpReward: 250,
    tasks: [
      "Set weekly weigh-in routine",
      "Track calories for 4 weeks",
      "Hit step count daily for a month",
      "Reach goal weight",
    ],
  },
  {
    id: "do-pullup",
    type: "side",
    category: "Health & Body",
    name: "Do my first unassisted pull-up",
    description: "From dead-hang to one clean rep.",
    icon: "🏋️",
    xpReward: 50,
    tasks: [
      "30s dead-hang",
      "5× negative pull-ups",
      "Banded pull-ups for 3 sets",
      "One unassisted rep",
    ],
  },
  {
    id: "meditate-30",
    type: "side",
    category: "Health & Body",
    name: "Meditate 30 days in a row",
    description: "10 minutes per day, no exceptions.",
    icon: "🧘",
    xpReward: 50,
  },

  // ===== Career & Money =====
  {
    id: "side-project-ship",
    type: "main",
    category: "Career & Money",
    name: "Ship a side project",
    description: "Build something small, polish it, and put it in the world.",
    icon: "🚀",
    xpReward: 200,
    tasks: [
      "Pick the idea",
      "MVP working end-to-end",
      "Get 5 friends to try it",
      "Ship publicly",
    ],
  },
  {
    id: "ask-for-raise",
    type: "side",
    category: "Career & Money",
    name: "Ask for a raise",
    description: "Build the case, schedule the talk, have it.",
    icon: "💼",
    xpReward: 100,
    tasks: [
      "Document last year's wins",
      "Research market rate",
      "Draft talking points",
      "Schedule the conversation",
      "Have the conversation",
    ],
  },
  {
    id: "emergency-fund",
    type: "main",
    category: "Career & Money",
    name: "Build a 3-month emergency fund",
    description: "Three months of expenses set aside in a savings account.",
    icon: "💰",
    xpReward: 250,
    tasks: [
      "Calculate monthly burn",
      "Open a dedicated savings account",
      "Automate monthly transfer",
      "Reach 1-month buffer",
      "Reach 3-month buffer",
    ],
  },
  {
    id: "learn-new-skill",
    type: "side",
    category: "Career & Money",
    name: "Learn a marketable new skill",
    description: "Pick one, do the work, ship something with it.",
    icon: "🧠",
    xpReward: 100,
  },

  // ===== Creativity =====
  {
    id: "write-novel",
    type: "main",
    category: "Creativity",
    name: "Write a novel",
    description: "First draft of a 60,000+ word novel.",
    icon: "✍️",
    xpReward: 500,
    tasks: [
      "Outline the plot",
      "Draft chapter 1",
      "Hit 20,000 words",
      "Hit 40,000 words",
      "Finish first draft",
    ],
  },
  {
    id: "release-album",
    type: "main",
    category: "Creativity",
    name: "Release a 5-song EP",
    description: "Write, record, mix, and put it on streaming services.",
    icon: "🎸",
    xpReward: 300,
    tasks: [
      "Demo all 5 songs",
      "Record final tracks",
      "Mix & master",
      "Make cover art",
      "Distribute (DistroKid / Bandcamp)",
    ],
  },
  {
    id: "art-show",
    type: "side",
    category: "Creativity",
    name: "Submit work to a juried show",
    description: "Make the work, polish it, send it in.",
    icon: "🎨",
    xpReward: 75,
  },
  {
    id: "blog-12-posts",
    type: "side",
    category: "Creativity",
    name: "Publish 12 blog posts in a year",
    description: "One per month — about anything you find interesting.",
    icon: "📝",
    xpReward: 100,
    tasks: [
      "Set up the blog",
      "Publish post 1",
      "Publish post 6",
      "Publish post 12",
    ],
  },
  {
    id: "short-film",
    type: "main",
    category: "Creativity",
    name: "Make a short film",
    description:
      "5–15 minutes, fully finished — script, shoot, cut, score, share.",
    icon: "🎬",
    xpReward: 250,
    tasks: [
      "Write the script",
      "Storyboard / shot list",
      "Cast & locations",
      "Principal photography",
      "Edit & sound",
      "Premiere screening",
    ],
  },
  {
    id: "photo-book",
    type: "side",
    category: "Creativity",
    name: "Self-publish a photo book",
    description:
      "Curate a year (or theme) of your photography into a printed book.",
    icon: "📷",
    xpReward: 100,
    tasks: [
      "Choose a theme & cull shots",
      "Sequence the layout",
      "Order a proof",
      "Final print run",
    ],
  },
  {
    id: "draw-100-days",
    type: "side",
    category: "Creativity",
    name: "100 days of drawing",
    description: "One sketch per day for 100 consecutive days.",
    icon: "✏️",
    xpReward: 150,
    tasks: [
      "Day 1–25",
      "Day 26–50",
      "Day 51–75",
      "Day 76–100",
    ],
  },
  {
    id: "open-mic",
    type: "side",
    category: "Creativity",
    name: "Perform at an open mic",
    description:
      "Music, comedy, poetry — pick one, prepare a 5-minute set, do it live.",
    icon: "🎤",
    xpReward: 75,
    tasks: [
      "Pick the piece",
      "Rehearse 10× through",
      "Find an open mic night",
      "Perform",
    ],
  },
  {
    id: "podcast-10",
    type: "side",
    category: "Creativity",
    name: "Launch a podcast — 10 episodes",
    description:
      "Concept, theme music, hosting, the lot. Quit before episode 10 doesn't count.",
    icon: "🎙️",
    xpReward: 200,
    tasks: [
      "Pick a topic & format",
      "Buy a decent mic",
      "Record episodes 1–3",
      "Publish on at least 2 platforms",
      "Reach episode 10",
    ],
  },
  {
    id: "youtube-channel",
    type: "main",
    category: "Creativity",
    name: "Start a YouTube channel — first 10 videos",
    description:
      "Pick a niche, post consistently, learn the craft as you go.",
    icon: "📹",
    xpReward: 250,
    tasks: [
      "Pick a niche & channel name",
      "Set up gear & basic editing flow",
      "Publish video 1",
      "Reach video 5",
      "Reach video 10",
    ],
  },
  {
    id: "graphic-novel",
    type: "main",
    category: "Creativity",
    name: "Make a 24-page graphic novella",
    description: "Write it, draw it, letter it, bind a copy.",
    icon: "📖",
    xpReward: 400,
    tasks: [
      "Write the script",
      "Thumbnail every page",
      "Pencil & ink the pages",
      "Letter & color",
      "Print a bound proof",
    ],
  },
  {
    id: "ceramics-set",
    type: "side",
    category: "Creativity",
    name: "Throw a complete dinner set",
    description: "Make a matching set of plates, bowls, and mugs on the wheel.",
    icon: "🏺",
    xpReward: 150,
    tasks: [
      "Take an intro wheel class",
      "Throw 4 plates",
      "Throw 4 bowls",
      "Throw 4 mugs",
      "Glaze & fire the set",
    ],
  },
  {
    id: "song-a-week",
    type: "side",
    category: "Creativity",
    name: "Write a song a week for a month",
    description: "Four finished songs in four weeks — quantity over polish.",
    icon: "🎶",
    xpReward: 100,
  },
  {
    id: "design-portfolio",
    type: "side",
    category: "Creativity",
    name: "Build a portfolio site",
    description:
      "Design + ship a personal site that actually represents your work.",
    icon: "🖼️",
    xpReward: 100,
    tasks: [
      "Audit existing work",
      "Pick 5–8 best pieces",
      "Design the site",
      "Build & deploy",
      "Share publicly",
    ],
  },
  {
    id: "learn-instrument",
    type: "main",
    category: "Creativity",
    name: "Learn a new instrument",
    description:
      "Pick one. Get to the point of playing 3 pieces well from memory.",
    icon: "🎹",
    xpReward: 300,
  },
  {
    id: "stand-up-set",
    type: "side",
    category: "Creativity",
    name: "Write & perform a 5-minute stand-up set",
    description: "Real jokes, real audience, real microphone.",
    icon: "🎭",
    xpReward: 100,
    tasks: [
      "Draft 10 minutes of material",
      "Cut to the best 5",
      "Rehearse out loud",
      "Perform live",
    ],
  },

  // ===== Adventure =====
  {
    id: "solo-trip",
    type: "side",
    category: "Adventure",
    name: "Take a solo trip",
    description: "Travel somewhere new on your own for at least 5 days.",
    icon: "🗺️",
    xpReward: 100,
  },
  {
    id: "summit-mountain",
    type: "main",
    category: "Adventure",
    name: "Summit a real mountain",
    description: "Pick one above 2,500m. Train, plan, climb.",
    icon: "🏔️",
    xpReward: 200,
    tasks: [
      "Pick the mountain",
      "Train weekly cardio",
      "Test gear on a hike",
      "Summit",
    ],
  },
  {
    id: "learn-language-basics",
    type: "side",
    category: "Adventure",
    name: "Hold a 5-minute conversation in a new language",
    description: "Past pleasantries — actual back-and-forth.",
    icon: "🌍",
    xpReward: 100,
  },
  {
    id: "long-distance-hike",
    type: "main",
    category: "Adventure",
    name: "Walk a long-distance trail",
    description:
      "100+ km on a named trail (Camino segment, GR-something, etc.) under your own steam.",
    icon: "🥾",
    xpReward: 250,
    tasks: [
      "Pick the trail & dates",
      "Plan stages & lodging",
      "Train with weighted hikes",
      "Start day 1",
      "Reach the finish",
    ],
  },
  {
    id: "scuba-cert",
    type: "side",
    category: "Adventure",
    name: "Get scuba certified",
    description:
      "Open Water certification — pool, theory, and actual ocean dives.",
    icon: "🤿",
    xpReward: 150,
    tasks: [
      "Book a course",
      "Pass the theory exam",
      "Complete pool training",
      "Complete open-water dives",
    ],
  },
  {
    id: "bike-tour",
    type: "side",
    category: "Adventure",
    name: "Self-supported bike tour — 3 days",
    description: "Panniers, a tent, and three days of riding to somewhere new.",
    icon: "🚴",
    xpReward: 100,
    tasks: [
      "Plan the route",
      "Test the loaded bike",
      "Day 1 — set off",
      "Day 3 — arrive",
    ],
  },
  {
    id: "stargazing-night",
    type: "side",
    category: "Adventure",
    name: "Stargazing in a dark-sky reserve",
    description: "Drive to real darkness. See the Milky Way properly at least once.",
    icon: "🌌",
    xpReward: 25,
  },
  {
    id: "country-30",
    type: "main",
    category: "Adventure",
    name: "Visit 30 countries",
    description:
      "Lifetime quest. Real visits — passport stamp, at least one night.",
    icon: "🛂",
    xpReward: 500,
  },
  {
    id: "ski-black",
    type: "side",
    category: "Adventure",
    name: "Ski (or snowboard) a black run cleanly",
    description: "No survival turns, no falls — controlled top to bottom.",
    icon: "🎿",
    xpReward: 100,
  },
  {
    id: "marathon-run",
    type: "main",
    category: "Adventure",
    name: "Finish a marathon",
    description:
      "42.195 km, official race, your own legs. Time goal optional.",
    icon: "🏅",
    xpReward: 400,
    tasks: [
      "Pick the race & sign up",
      "Follow a 16–20 week plan",
      "Long run > 30 km",
      "Race day",
    ],
  },
  {
    id: "kayak-overnight",
    type: "side",
    category: "Adventure",
    name: "Kayak with an overnight stop",
    description:
      "Paddle out, camp on a beach or shore, paddle back. Self-supported.",
    icon: "🛶",
    xpReward: 75,
  },
  {
    id: "road-trip",
    type: "side",
    category: "Adventure",
    name: "Plan & take a 2,000 km road trip",
    description: "Multi-stop, real planning, no flying.",
    icon: "🚗",
    xpReward: 100,
    tasks: [
      "Pick the route",
      "Book the stops",
      "Make a great playlist",
      "Drive it",
    ],
  },
  {
    id: "sunrise-summit",
    type: "side",
    category: "Adventure",
    name: "Watch sunrise from a summit",
    description:
      "Hike up in the dark, watch the sun come over the horizon, hike down.",
    icon: "🌄",
    xpReward: 50,
  },
  {
    id: "northern-lights",
    type: "side",
    category: "Adventure",
    name: "See the northern lights",
    description: "Travel to the right latitude at the right time of year.",
    icon: "🌠",
    xpReward: 150,
  },
  {
    id: "open-water-swim",
    type: "side",
    category: "Adventure",
    name: "Open-water swim event — 1 km+",
    description: "Lake or sea, official event, no pool walls to push off.",
    icon: "🏊",
    xpReward: 100,
  },
  {
    id: "coast-to-coast",
    type: "main",
    category: "Adventure",
    name: "Cross a country coast-to-coast",
    description:
      "Cycling, walking, or driving — but slowly. From one sea to the other.",
    icon: "🌊",
    xpReward: 400,
  },

  // ===== Relationships =====
  {
    id: "host-dinner",
    type: "side",
    category: "Relationships",
    name: "Host a dinner party for 6+",
    description: "Plan it, cook it, enjoy it.",
    icon: "🍽️",
    xpReward: 50,
    tasks: [
      "Pick a date and guest list",
      "Plan the menu",
      "Shop & prep",
      "Host",
    ],
  },
  {
    id: "reconnect-old-friend",
    type: "side",
    category: "Relationships",
    name: "Reconnect with an old friend",
    description: "Reach out, set a real plan, follow through.",
    icon: "🤝",
    xpReward: 25,
  },
  {
    id: "weekly-call",
    type: "side",
    category: "Relationships",
    name: "Call a family member weekly for 3 months",
    description: "Same time every week — make it a ritual.",
    icon: "📞",
    xpReward: 50,
  },
  {
    id: "letters-three",
    type: "side",
    category: "Relationships",
    name: "Write three handwritten letters",
    description:
      "Pen, paper, post. Three people who'd be surprised to hear from you.",
    icon: "💌",
    xpReward: 30,
  },
  {
    id: "monthly-friend-night",
    type: "side",
    category: "Relationships",
    name: "Monthly friend night — 6 months",
    description:
      "Same group, same standing date, six months in a row. Hard mode: in person.",
    icon: "🍻",
    xpReward: 75,
  },
  {
    id: "long-trip-with-friend",
    type: "side",
    category: "Relationships",
    name: "Take a 5+ day trip with a close friend",
    description: "Just the two of you (or the small group). Real travel, real time.",
    icon: "✈️",
    xpReward: 100,
  },
  {
    id: "ask-out",
    type: "side",
    category: "Relationships",
    name: "Ask someone out you've been putting off",
    description: "The hard one. Ask once, kindly, regardless of the answer.",
    icon: "💘",
    xpReward: 50,
  },
  {
    id: "weekend-with-parents",
    type: "side",
    category: "Relationships",
    name: "Spend a weekend with your parents",
    description:
      "On purpose, undistracted. Cook a meal, take a walk, ask real questions.",
    icon: "👵",
    xpReward: 50,
  },
  {
    id: "interview-elder",
    type: "side",
    category: "Relationships",
    name: "Interview an older family member",
    description:
      "Record an hour or two of stories. They won't be around forever.",
    icon: "🎙️",
    xpReward: 75,
    tasks: [
      "Make a list of questions",
      "Set a date & explain",
      "Record the conversation",
      "Save it somewhere safe",
    ],
  },
  {
    id: "thank-you-five",
    type: "side",
    category: "Relationships",
    name: "Thank five people who shaped you",
    description:
      "Specifically — what they did, why it mattered. Letter, voice memo, or in person.",
    icon: "🙏",
    xpReward: 50,
  },
  {
    id: "book-club",
    type: "side",
    category: "Relationships",
    name: "Start (or join) a book club",
    description: "Six months of meetings, at least three books.",
    icon: "📚",
    xpReward: 75,
  },
  {
    id: "plan-surprise",
    type: "side",
    category: "Relationships",
    name: "Plan a surprise for someone you love",
    description: "Real effort, real thought — birthday, anniversary, or no reason.",
    icon: "🎁",
    xpReward: 50,
  },
  {
    id: "regular-meeting",
    type: "side",
    category: "Relationships",
    name: "Set up a recurring meet-up with a mentor",
    description: "Or be a mentor. Either way — make it monthly, keep it for a year.",
    icon: "🧓",
    xpReward: 100,
  },
  {
    id: "make-three-friends",
    type: "main",
    category: "Relationships",
    name: "Make three new real friendships",
    description:
      "Beyond acquaintance — people you'd call when something good (or bad) happens.",
    icon: "✨",
    xpReward: 200,
  },
  {
    id: "host-stranger",
    type: "side",
    category: "Relationships",
    name: "Host or attend a stranger-meet event",
    description:
      "Dinner club, language exchange, hobby meetup — show up, talk to people.",
    icon: "🫱",
    xpReward: 50,
  },
  {
    id: "couples-trip",
    type: "side",
    category: "Relationships",
    name: "Plan a getaway for your partner",
    description:
      "End-to-end planning by you. They just have to show up and enjoy.",
    icon: "💞",
    xpReward: 75,
  },

  // ===== Home =====
  {
    id: "declutter-home",
    type: "side",
    category: "Home",
    name: "Declutter the whole home",
    description: "Room by room. Donate / discard / keep.",
    icon: "🏠",
    xpReward: 75,
    tasks: [
      "Bedroom",
      "Closet",
      "Kitchen",
      "Living room",
      "Garage / storage",
    ],
  },
  {
    id: "garden-grow",
    type: "side",
    category: "Home",
    name: "Grow something edible from seed to plate",
    description: "Pick a vegetable or herb. See it through.",
    icon: "🌱",
    xpReward: 50,
  },
  {
    id: "deep-clean",
    type: "side",
    category: "Home",
    name: "Deep clean every room",
    description:
      "Behind the appliances, inside the cabinets, the kind that takes a weekend.",
    icon: "🧽",
    xpReward: 50,
    tasks: [
      "Kitchen — appliances out",
      "Bathroom — top to bottom",
      "Bedrooms — under furniture",
      "Living spaces",
      "Outdoor / windows",
    ],
  },
  {
    id: "paint-room",
    type: "side",
    category: "Home",
    name: "Paint a room properly",
    description: "Patch, prime, two coats — not a slapdash job.",
    icon: "🎨",
    xpReward: 75,
    tasks: [
      "Pick the colour",
      "Patch & sand walls",
      "Tape & prime",
      "Two finish coats",
      "Reinstall trim & furniture",
    ],
  },
  {
    id: "build-furniture",
    type: "side",
    category: "Home",
    name: "Build a piece of furniture from scratch",
    description: "Real wood, real joinery, no flat-pack.",
    icon: "🪚",
    xpReward: 150,
    tasks: [
      "Pick a project & buy plans",
      "Source the wood",
      "Cut & joint",
      "Assemble",
      "Finish (oil / stain / paint)",
    ],
  },
  {
    id: "veggie-garden",
    type: "main",
    category: "Home",
    name: "Set up a productive veggie garden",
    description:
      "Beds, soil, irrigation, a planting plan — and actually eat from it.",
    icon: "🥕",
    xpReward: 200,
    tasks: [
      "Pick the spot & build beds",
      "Soil & compost",
      "Plant first round",
      "Set up watering",
      "Harvest a real meal",
    ],
  },
  {
    id: "compost",
    type: "side",
    category: "Home",
    name: "Set up a compost system",
    description:
      "Indoor or outdoor — whatever fits your home. Use it for at least 3 months.",
    icon: "🪱",
    xpReward: 50,
  },
  {
    id: "organize-paperwork",
    type: "side",
    category: "Home",
    name: "Organize all paperwork & finances",
    description:
      "Insurance, taxes, contracts, receipts — sorted, labeled, scanned, findable.",
    icon: "🗄️",
    xpReward: 100,
    tasks: [
      "Gather everything in one pile",
      "Sort into categories",
      "Scan to digital archive",
      "Shred / file what's left",
    ],
  },
  {
    id: "emergency-kit",
    type: "side",
    category: "Home",
    name: "Build a household emergency kit",
    description:
      "Water, food, light, first aid, important documents — for at least 72 hours.",
    icon: "🧯",
    xpReward: 50,
    tasks: [
      "Make the checklist",
      "Buy / gather supplies",
      "Document copies in a fire-safe spot",
      "Test the kit on a power-out drill",
    ],
  },
  {
    id: "smart-home",
    type: "side",
    category: "Home",
    name: "Set up a basic smart-home system",
    description:
      "Lights, thermostat, or whatever matters most — automated, working reliably.",
    icon: "💡",
    xpReward: 75,
  },
  {
    id: "create-workshop",
    type: "main",
    category: "Home",
    name: "Build out a dedicated workspace",
    description:
      "Desk, lighting, tools, storage — a place where you can actually work on the thing you care about.",
    icon: "🛠️",
    xpReward: 200,
    tasks: [
      "Pick the room / corner",
      "Clear & clean the space",
      "Get the bench / desk in",
      "Lighting & power sorted",
      "Tools / supplies organized",
    ],
  },
  {
    id: "refinish-floor",
    type: "side",
    category: "Home",
    name: "Refinish a wooden floor",
    description: "Sand, stain, seal. One weekend or a few — but do it right.",
    icon: "🪵",
    xpReward: 150,
  },
  {
    id: "bake-bread-month",
    type: "side",
    category: "Home",
    name: "Bake bread weekly for a month",
    description:
      "Sourdough, focaccia, soda bread — pick a style and master one loaf.",
    icon: "🍞",
    xpReward: 50,
  },
  {
    id: "fermentation",
    type: "side",
    category: "Home",
    name: "Ferment three different things",
    description:
      "Sauerkraut, kombucha, kimchi, hot sauce, miso — pick three, eat the results.",
    icon: "🥒",
    xpReward: 75,
  },
  {
    id: "guest-room-ready",
    type: "side",
    category: "Home",
    name: "Make a proper guest setup",
    description:
      "Dedicated guest bedding, towels, a key — guests can stay without warning.",
    icon: "🛏️",
    xpReward: 50,
  },
  {
    id: "home-library",
    type: "side",
    category: "Home",
    name: "Build a real home library",
    description:
      "Dedicated shelving, organized, lit well — a room (or wall) you actually want to read in.",
    icon: "📚",
    xpReward: 100,
  },
  {
    id: "rain-barrel",
    type: "side",
    category: "Home",
    name: "Install a rain barrel",
    description:
      "Catch and use rainwater for the garden. Small project, surprisingly satisfying.",
    icon: "🌧️",
    xpReward: 40,
  },
  {
    id: "energy-audit",
    type: "side",
    category: "Home",
    name: "Run an energy audit & fix the top 3 leaks",
    description:
      "Find where the heat / power escapes. Seal, insulate, swap bulbs.",
    icon: "🔌",
    xpReward: 75,
    tasks: [
      "Read last 12 months of bills",
      "Walk through with a thermal cam (or rented one)",
      "Pick top 3 fixes",
      "Do the fixes",
    ],
  },
  {
    id: "host-housewarming",
    type: "side",
    category: "Home",
    name: "Host a housewarming",
    description:
      "Whether you've lived there a month or ten years — invite people in, show it off.",
    icon: "🥂",
    xpReward: 40,
  },
];

export function getQuestTemplate(id: string): QuestTemplate | null {
  return QUEST_TEMPLATES.find((t) => t.id === id) ?? null;
}

export function listQuestTemplateCategories(): string[] {
  const seen = new Set<string>();
  const order: string[] = [];
  for (const t of QUEST_TEMPLATES) {
    if (!seen.has(t.category)) {
      seen.add(t.category);
      order.push(t.category);
    }
  }
  return order;
}
